#!/bin/bash
#PBS -N XANES_sq_3
#PBS -r y
#PBS -q main
#PBS -W group_list=catalys
#PBS -l walltime=06:00:00 
#PBS -l select=1:ncpus=12:mem=30000mb:mpiprocs=12:ompthreads=1
#PBS -M jan.kloppenburg@uclouvain.be
#PBS -m ae

cd /home/acad/ucl-naps/jank/catalys/projects/SrIrO3/bulk/SrIrO3/brownmillerite/3_plus/sq/3

python ~/python-tools/xanes/pmg_xanes.py
